// TREND //
export const FETCH_TREND_SUCCESS = 'FETCH_TREND_SUCCESS';
export const FETCh_TREND_ERROR = 'FETCh_TREND_ERROR';

// RESIDUAL PLOT //
export const FETCH_RESIDUAL_PLOT_SUCCESS = 'FETCH_RESIDUAL_PLOT_SUCCESS';
export const FETCH_RESIDUAL_PLOT_ERROR = 'FETCH_RESIDUAL_PLOT_ERROR';

// RESIDUAL HISTOGRAM //
export const FETCH_RESIDUAL_HIST_SUCCESS = 'FETCH_RESIDUAL_HIST_SUCCESS';
export const FETCH_RESIDUAL_HIST_ERROR = 'FETCH_RESIDUAL_HIST_ERROR';

// QQ PLOT //
export const FETCH_QQ_PLOT_SUCCESS = 'FETCH_QQ_PLOT_SUCCESS';
export const FETCH_QQ_PLOT_ERROR = 'FETCH_QQ_PLOT_ERROR';

// PROBABILITY PLOT //
export const FETCH_PROB_PLOT_SUCCESS = 'FETCH_PROB_PLOT_SUCCESS';
export const FETCH_PROB_PLOT_ERROR = 'FETCH_PROB_PLOT_ERROR';