// TREND //
export const FETCH_TREND_SUCCESS = 'FETCH_TREND_SUCCESS';
export const FETCh_TREND_ERROR = 'FETCh_TREND_ERROR';

// RESIDUAL PLOT //
export const FETCH_RESIDUAL_PLOT_SUCCESS = 'FETCH_RESIDUAL_PLOT_SUCCESS';
export const FETCH_RESIDUAL_PLOT_ERROR = 'FETCH_RESIDUAL_PLOT_ERROR';

// RESIDUAL HISTOGRAM //
export const FETCH_RESIDUAL_HIST_SUCCESS = 'FETCH_RESIDUAL_HIST_SUCCESS';
export const FETCH_RESIDUAL_HIST_ERROR = 'FETCH_RESIDUAL_HIST_ERROR';

// QQ PLOT //
export const FETCH_QQ_PLOT_SUCCESS = 'FETCH_QQ_PLOT_SUCCESS';
export const FETCH_QQ_PLOT_ERROR = 'FETCH_QQ_PLOT_ERROR';

// PROBABILITY PLOT //
export const FETCH_PROB_PLOT_SUCCESS = 'FETCH_PROB_PLOT_SUCCESS';
export const FETCH_PROB_PLOT_ERROR = 'FETCH_PROB_PLOT_ERROR';

// METRIC //
export const FETCH_METRIC_SUCCESS = 'FETCH_METRIC_SUCCESS';
export const FETCH_METRIC_ERROR = 'FETCH_METRIC_ERROR';

// MODAL //
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// DASHBOARD NAVIGATION //
export const LOAD_DASHBOARD_PAGE_SUCCESS = 'LOAD_DASHBOARD_PAGE_SUCCESS';

// DATA STEPS NAVIGATION //
export const NEXT_DATA_STEP = 'NEXT_DATA_STEP';
export const PREV_DATA_STEP = 'PREV_DATA_STEP';
export const ENABLE_DOWNLOADS = 'ENABLE_DOWNLOADS';

// RESEARCH //
export const TOGGLE_TAG = 'TOGGLE_TAG';